global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Основной воркер менеджер
  - job_name: 'layout-worker-manager'
    static_configs:
      - targets: ['layout_worker_manager:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  # Системные метрики контейнеров
  - job_name: 'docker-containers'
    static_configs:
      - targets: ['layout_worker_1:8001', 'layout_worker_2:8001', 'optimization_worker:8001', 'persistence_worker:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis метрики
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Prometheus самого себя
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
